services:
  - type: web
    name: mood-ml-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ml_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
